<a href="https://colab.research.google.com/github/Abhishekpardhi46/MSC_MLDL/blob/main/DecisionTreeClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [186]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [187]:
dataset = pd.read_csv('Social_Network_Ads.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [188]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.25)

In [189]:
print(x_train)

[[    25  80000]
 [    33  28000]
 [    46  59000]
 [    52 138000]
 [    40  59000]
 [    29  80000]
 [    39  71000]
 [    47  30000]
 [    38  50000]
 [    30  62000]
 [    53 104000]
 [    42  54000]
 [    35  73000]
 [    59  76000]
 [    42  54000]
 [    26  81000]
 [    22  81000]
 [    43 112000]
 [    35  79000]
 [    37  71000]
 [    39  59000]
 [    29 148000]
 [    23  20000]
 [    42  80000]
 [    31  76000]
 [    47  51000]
 [    48 131000]
 [    40  72000]
 [    49 141000]
 [    26  80000]
 [    36 118000]
 [    42 104000]
 [    34  72000]
 [    26  15000]
 [    38  51000]
 [    29  47000]
 [    59 143000]
 [    31  89000]
 [    27  20000]
 [    38 112000]
 [    42  90000]
 [    47 144000]
 [    38  65000]
 [    29  43000]
 [    21  72000]
 [    31  71000]
 [    37  72000]
 [    35  25000]
 [    20  82000]
 [    37  33000]
 [    46  82000]
 [    24  58000]
 [    59  42000]
 [    20  36000]
 [    18  68000]
 [    56 104000]
 [    35 108000]
 [    27  54000]
 [    43 13300

In [190]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [191]:
print(x_train)

[[-1.17083435  0.33775151]
 [-0.40828281 -1.21147622]
 [ 0.83086345 -0.28789815]
 [ 1.40277711  2.06573627]
 [ 0.25894979 -0.28789815]
 [-0.78955858  0.33775151]
 [ 0.16363085  0.06961594]
 [ 0.9261824  -1.15189054]
 [ 0.06831191 -0.55603372]
 [-0.69423963 -0.19851963]
 [ 1.49809605  1.05277969]
 [ 0.44958768 -0.43686236]
 [-0.21764492  0.12920162]
 [ 2.07000971  0.21858014]
 [ 0.44958768 -0.43686236]
 [-1.07551541  0.36754435]
 [-1.45679118  0.36754435]
 [ 0.54490662  1.29112241]
 [-0.21764492  0.30795866]
 [-0.02700703  0.06961594]
 [ 0.16363085 -0.28789815]
 [-0.78955858  2.36366468]
 [-1.36147223 -1.44981894]
 [ 0.44958768  0.33775151]
 [-0.59892069  0.21858014]
 [ 0.9261824  -0.52624088]
 [ 1.02150134  1.85718639]
 [ 0.25894979  0.09940878]
 [ 1.11682028  2.1551148 ]
 [-1.07551541  0.33775151]
 [-0.12232598  1.46987946]
 [ 0.44958768  1.05277969]
 [-0.31296386  0.09940878]
 [-1.07551541 -1.59878315]
 [ 0.06831191 -0.52624088]
 [-0.78955858 -0.64541224]
 [ 2.07000971  2.21470048]
 

In [192]:
print(x_test)

[[ 0.9261824  -1.44981894]
 [-0.21764492  0.24837298]
 [-0.88487752 -0.40706952]
 [ 1.30745817  1.94656491]
 [ 0.35426874  0.54630139]
 [-0.31296386  1.29112241]
 [ 0.35426874 -0.28789815]
 [-0.02700703 -0.19851963]
 [-1.26615329 -1.09230485]
 [ 1.02150134  0.81443696]
 [-0.12232598 -0.16872679]
 [ 0.06831191 -0.40706952]
 [-1.07551541  0.33775151]
 [-0.59892069 -1.59878315]
 [ 0.16363085  1.58905082]
 [ 2.07000971  1.82739355]
 [ 0.06831191 -0.28789815]
 [-0.69423963  0.54630139]
 [ 2.07000971 -1.18168338]
 [ 1.02150134 -1.06251201]
 [-1.07551541 -1.00292633]
 [ 1.593415    1.17195105]
 [ 0.16363085  1.94656491]
 [ 1.30745817 -1.36044042]
 [ 0.9261824  -1.36044042]
 [-0.02700703  0.27816582]
 [-1.07551541  0.09940878]
 [ 0.35426874 -0.49644804]
 [ 1.21213922 -1.44981894]
 [-0.98019646 -0.31769099]
 [-1.55211012 -0.01976258]
 [-0.02700703  0.1887873 ]
 [-0.02700703  0.72505844]
 [-0.31296386 -0.76458361]
 [-0.21764492 -0.40706952]
 [-0.31296386  1.38050093]
 [ 2.16532865 -1.03271917]
 

In [193]:
print(y_train)

[0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 1
 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0
 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1
 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 1 1 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 0 1 0 0 1 1 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0
 1 0 1 0]


In [194]:
print(y_test)

[1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 1
 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 0 0 0
 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 1]


In [195]:
from sklearn.tree import DecisionTreeClassifier
dct = DecisionTreeClassifier()
dct.fit(x_train, y_train)

DecisionTreeClassifier()

In [196]:
y_pred = dct.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


In [197]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
print(cm)
accuracy_score(y_pred,y_test)

[[55  4]
 [ 4 37]]


0.92